name: Deploy til GitHub Pages

on:
  push:
    branches:
      - main # Kjører når du pusher til main

  workflow_dispatch: # Mulighet for manuell deploy fra GitHub Actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode fra GitHub
        uses: actions/checkout@v4

      - name: Sett opp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer avhengigheter
        run: npm install

      - name: Bygg prosjektet
        run: npm run build

      - name: Last opp bygget til GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist # Bytt ut med korrekt build-mappe hvis den heter noe annet

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy til GitHub Pages
        uses: actions/deploy-pages@v2
