name: Deploy til GitHub Pages

on:
  push:
    branches:
      - main # Kjør når vi pusher til main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode fra GitHub
        uses: actions/checkout@v4

      - name: Sett opp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer avhengigheter
        run: npm install

      - name: Bygg prosjektet
        run: npm run build

      - name: Deploy til GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist # Sørg for at vite.config.js peker riktig

      - name: Publiser til GitHub Pages
        uses: actions/deploy-pages@v2
